#!/usr/bin/env node

var express = require('express');
var ecstatic = require('ecstatic');

var app = express.createServer(),
    root = __dirname;
app.use(ecstatic(root));
app.listen(8000);

console.log('Serving ' + root);
console.log('Listening on :8000');
